# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Epic games

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 */2 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Firfox webdriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
        tar xf geckodriver-v0.29.1-linux64.tar.gz
        echo "${PWD}" >> $GITHUB_PATH

    - name: Run `get_games.py`
      run: |
        python get_games.py
        
    - name: Run `check_and_send_email.py`
      run: |
        python check_and_send_email.py   
      env:
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        RECEIVER: ${{ secrets.RECEIVER }}
          
    - name: Push changes to repo
      uses: actions-x/commit@v2
      with:
        email: ${{ secrets.EMAIL_HOST_USER }}
        name: GitHub Actions Auto committer
        branch: main
        files: new_games.csv old_games.csv 
        repository: https://github.com/behnambm/auto-email-epicgames
        token: ${{ secrets.GITHUB_TOKEN }}
#         force: true
        
        
        
        

