# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Epic games

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 */1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox web driver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
        tar xf geckodriver-v0.29.1-linux64.tar.gz
        echo "${PWD}" >> $GITHUB_PATH

    - name: Run `get_games.py`
      run: |
        python get_games.py
        
    - name: Run `update_channel.py`
      run: |
        python update_channel.py   
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    
    - name: Make dir safe
      run: git config --global --add safe.directory /github 

    - name: Push changes to repo
      uses: actions-x/commit@v2
      env:
        GIT_CEILING_DIRECTORIES: /github
      with:
        email: behnam.mohamadzadeh21@gmail.com
        name: GitHub Actions Auto committer
        branch: main
        files: new_games.csv old_games.csv 
        repository: https://github.com/behnambm/auto-update-epicgames
        token: ${{ secrets.GITHUB_TOKEN }}
#         force: true
        
        
        
        

