# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Epic games

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Firfox webdriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
        tar xf geckodriver-v0.29.1-linux64.tar.gz
        echo "${PWD}" >> $GITHUB_PATH

    - name: Run `get_games.py`
      run: |
        python get_games.py
        
        
        

